//tealium universal tag - utag.19 ut4.0.202108031711, Copyright 2021 Tealium.com Inc. All Rights Reserved.
try{(function(id,loader,u){try{u=utag.o[loader].sender[id]={};}catch(e){u=utag.sender[id];}
u.id=id;u.ev={"view":1};u.map={"trade_desk_ct":"ct"};u.extend=[function(a,b){try{if(b['page_name'].toString().toLowerCase()=='confirmation'.toLowerCase()){b['trade_desk_ct']='ljveg09'}}catch(e){utag.DB(e);}}];u.send=function(a,b,c,d,e,f){if(u.ev[a]||typeof u.ev.all!="undefined"){utag.DB("send:19");utag.DB(b);u.qsp_delim="&";u.kvp_delim="=";u.type="conv";u.adv="yg40rp0";u.ct="ejl1aw3";u.fmt="3";u.pid="";u.coid="";u.base_url="//insight.adsrvr.org";for(c=0;c<u.extend.length;c++){try{d=u.extend[c](a,b);if(d==false)return}catch(e){}};utag.DB("send:19:EXTENSIONS");utag.DB(b);c=[];for(d in utag.loader.GV(u.map)){if(typeof b[d]!=="undefined"&&b[d]!==""){e=u.map[d].split(",");for(f=0;f<e.length;f++){if(e[f]=="ct"||e[f]=="adv"){u[e[f]]=b[d];}else{c.push(e[f]+u.kvp_delim+encodeURIComponent(b[d]));}}}}
if(u.fmt==="")u.fmt="3";if((u.type==="iframe"&&u.fmt==="3")||(u.type!=="iframe"&&u.fmt==="1")){utag.DB("Tag "+id+": The fmt and tag types do not match (e.g., if fmt = 1, then type should be iframe). This may negatively affect tag functionality. Please ensure that the tag is correctly configured.");}
if(u.type=="iframe"){u.base_url+="/tags/"+u.adv+"/"+u.ct+"/iframe";d=document.createElement("iframe");d.setAttribute("id","19");d.setAttribute("height","1");d.setAttribute("width","1");d.setAttribute("style","display:none");d.setAttribute("src",u.base_url);document.body.appendChild(d);}else{if(u.pid){c.push("pid"+u.kvp_delim+u.pid);}
c.push("fmt"+u.kvp_delim+u.fmt);if(b._corder){c.push("v"+u.kvp_delim+((b._csubtotal)?b._csubtotal:"1"));c.push("vf"+u.kvp_delim+b._ccurrency);c.push("orderId"+u.kvp_delim+b._corder);}
if(u.coid){c.push("coid"+u.kvp_delim+u.coid);}
u.base_url+="/track/"+u.type+"/?ct"+u.kvp_delim+u.ct+u.qsp_delim+"adv"+u.kvp_delim+u.adv+u.qsp_delim;if(u.fmt=="3"){u.img=new Image();u.img.src=u.base_url+c.join(u.qsp_delim);}else{d=document.createElement("iframe");d.setAttribute("id","19");d.setAttribute("height","1");d.setAttribute("width","1");d.setAttribute("style","display:none");d.setAttribute("src",u.base_url+c.join(u.qsp_delim));document.body.appendChild(d);}}}
utag.DB("send:19:COMPLETE");}
try{utag.o[loader].loader.LOAD(id);}catch(e){utag.loader.LOAD(id);}})("19","underarmour.main");}catch(error){utag.DB(error);}
