//tealium universal tag - utag.90 ut4.0.202110062035, Copyright 2021 Tealium.com Inc. All Rights Reserved.
try{(function(id,loader){var u={"id":id};utag.o[loader].sender[id]=u;if(utag.ut===undefined){utag.ut={};}
if(utag.ut.loader===undefined){u.loader=function(o){var b,c,l,a=document;if(o.type==="iframe"){b=a.createElement("iframe");o.attrs=o.attrs||{"height":"1","width":"1","style":"display:none"};for(l in utag.loader.GV(o.attrs)){b.setAttribute(l,o.attrs[l]);}b.setAttribute("src",o.src);}else if(o.type=="img"){utag.DB("Attach img: "+o.src);b=new Image();b.src=o.src;return;}else{b=a.createElement("script");b.language="javascript";b.type="text/javascript";b.async=1;b.charset="utf-8";for(l in utag.loader.GV(o.attrs)){b[l]=o.attrs[l];}b.src=o.src;}if(o.id){b.id=o.id};if(typeof o.cb=="function"){if(b.addEventListener){b.addEventListener("load",function(){o.cb()},false);}else{b.onreadystatechange=function(){if(this.readyState=='complete'||this.readyState=='loaded'){this.onreadystatechange=null;o.cb()}};}}l=o.loc||"head";c=a.getElementsByTagName(l)[0];if(c){utag.DB("Attach to "+l+": "+o.src);if(l=="script"){c.parentNode.insertBefore(b,c);}else{c.appendChild(b)}}}}else{u.loader=utag.ut.loader;}
u.encode=function(a,b){b="";try{b=encodeURIComponent(a)}catch(e){utag.DB(e);}if(b==""){b=escape(a);}return b}
u.ev={"view":1};u.scriptrequested=false;u.rp=function(a,b){if(typeof a!=="undefined"&&a.indexOf("@@")>0){a=a.replace(/@@([^@]+)@@/g,function(m,d){if(b[d]){return u.encode(b[d]);}else{return"";}});}
return a;};u.map={};u.extend=[function(a,b){try{if(1){(function movablePixel(pageData){(function(m,o,v,a,b,l,e){if(typeof m['MovableInkTrack']!=='undefined'){return;}
m['MovableInkTrack']=b;l=o.createElement(v);e=o.getElementsByTagName(v)[0];l.type='text/javascript';l.async=true;l.src='//'+a+'/p/js/1.js';m[b]=m[b]||function(){(m[b].q=m[b].q||[]).push(arguments);};e.parentNode.insertBefore(l,e);})(window,document,'script','o2jjubsv.micpn.com','mitr');if(pageData.page_type==='order-receipt'){(pageData.product_sku||[]).forEach(function addMitrProduct(sku,index){window.mitr('addProduct',{sku:pageData.product_sku[index],name:pageData.product_name[index],price:pageData.product_line_item_revenue[index],quantity:pageData.product_quantity[index]});});(pageData.order_promo_codes||[]).forEach(function addMitrPromoCode(sku,idx){if(['source-code','coupon'].includes(pageData.order_promo_trigger_types[idx])){window.mitr('addPromo',{code:pageData.order_promo_codes[idx]});}});if(pageData.order_total&&pageData.order_id){window.mitr('send','conversion',{revenue:pageData.order_total,identifier:pageData.order_id});}}})(b);}}catch(e){utag.DB(e)}},function(a,b){try{if(1){(function youtubePixel(pageData,uaGlobalTools){uaGlobalTools.loadScript('https://www.googletagmanager.com/gtag/js?id=AW-619920358',true);window.dataLayer=window.dataLayer||[];window.gtag=function gtag(){dataLayer.push(arguments);}
window.gtag('js',new Date());window.gtag('config','AW-619920358');if(pageData.page_type==='order-receipt'){window.gtag('event','conversion',{'send_to':'AW-619920358/Ts19CMvk2dUBEOb3zKcC'});}})(b,utag.uaGlobalTools);}}catch(e){utag.DB(e)}},function(a,b){try{if(1){(function branchSDKPixel(){(function branchSDKScript(b,r,a,n,c,h,_,s,d,k){if(!b[n]||!b[n]._q){for(;s<_.length;)c(h,_[s++]);d=r.createElement(a);d.async=1;d.src="https://cdn.branch.io/branch-latest.min.js";k=r.getElementsByTagName(a)[0];k.parentNode.insertBefore(d,k);b[n]=h}})(window,document,"script","branch",function(b,r){b[r]=function(){b._q.push([r,arguments])}},{_q:[],_v:1},"addListener applyCode autoAppIndex banner closeBanner closeJourney creditHistory credits data deepview deepviewCta first getCode init link logout redeem referrals removeListener sendSMS setBranchViewData setIdentity track validateCode trackCommerceEvent logEvent disableTracking".split(" "),0);branch.init('key_live_bobZZ2RUuxSOMiBwOzpCscjntwlpVaac');})();}}catch(e){utag.DB(e)}},function(a,b){try{if(1){(function UnidaysPixel(pageData,uaGlobalTools){if(pageData.page_type!=='order-receipt'){return;}
var REGION_AU_NZ=(pageData.site_country_code==='AU'||pageData.site_country_code==='NZ');var hasUnidaysPromo=false;var unidaysPromoCode='';var itemsUnidaysDiscount=0;if(REGION_AU_NZ){(pageData.order_promo_codes||[]).forEach(function mapPromoClasses(promoClass,idx){if(pageData.order_promo_codes[idx].indexOf('UD15')===0){hasUnidaysPromo=true;unidaysPromoCode=pageData.order_promo_codes[idx];itemsUnidaysDiscount=pageData.order_discount;}});}else{(pageData.order_promo_classes||[]).forEach(function mapPromoClasses(promoClass,idx){if(pageData.order_promo_codes[idx].indexOf('STU-')===0){hasUnidaysPromo=true;unidaysPromoCode=pageData.order_promo_codes[idx];itemsUnidaysDiscount=pageData.order_promo_discount[idx];}});}
if(!hasUnidaysPromo){return;}
uaGlobalTools.loadScriptWithFunction('https://cdn.unidays.world/unidays-tracking.min.js',function unidaysPixel(){var pixelID=(pageData.site_country_code==='CA')?'ihLmYodcXUKzjQVDx5sfYH7PdnxjVAJAut1G4heWaTQ=':'ihLmYodcXUKzjQVDx5sfYDR/8HZ4fEdLrLAnpbEKnwg=';var currencyCode=pageData.site_currency;var orderID=pageData.order_id;var itemsTax=(REGION_AU_NZ)?pageData.order_merchandizing_tax:pageData.order_merchandize_tax;var shippingGross=uaGlobalTools.stringMoneySubtract(pageData.order_shipping_subtotal,pageData.order_shipping_tax);var shippingDiscount=pageData.order_shipping_discount||0;var itemsGross=uaGlobalTools.stringMoneyAdd([pageData.order_subtotal,itemsTax]);var itemsOtherDiscount=uaGlobalTools.stringMoneySubtract(pageData.order_discount,itemsUnidaysDiscount);var unidaysDiscountPercentage;if(REGION_AU_NZ){unidaysDiscountPercentage=uaGlobalTools.stringMoneyMultiply(100,uaGlobalTools.stringMoneyDivide(itemsUnidaysDiscount,uaGlobalTools.stringMoneyAdd([pageData.order_subtotal,itemsTax])));}else{unidaysDiscountPercentage=uaGlobalTools.stringMoneyMultiply(100,uaGlobalTools.stringMoneyDivide(itemsUnidaysDiscount,pageData.order_subtotal));}
var newCustomer=pageData.customer_type==='New';var orderTotal=pageData.order_total;var unidaysObject=new UnidaysTracking(pixelID,currencyCode,orderID,unidaysPromoCode);unidaysObject.trackingScriptRequest(orderTotal,itemsUnidaysDiscount,itemsTax,shippingGross,shippingDiscount,itemsGross,itemsOtherDiscount,unidaysDiscountPercentage,newCustomer);});})(b,utag.uaGlobalTools);}}catch(e){utag.DB(e)}}];u.send=function(a,b){if(u.ev[a]||u.ev.all!==undefined){var c,d,e,f;u.data={"qsp_delim":"&"||"&","kvp_delim":"="||"=","qs_delim":"?"||"?","tag_type":"script","base_url":"","secure_base_url":"","static_params":"","cachebust":"disabled","cachevar":""||"_rnd","requestscriptonce":"disabled"};for(c=0;c<u.extend.length;c++){try{d=u.extend[c](a,b);if(d==false)return}catch(e){}};utag.DB("send:90:EXTENSIONS");utag.DB(b);c=[];for(d in utag.loader.GV(u.map)){if(typeof b[d]!=="undefined"&&b[d]!==""){e=u.map[d].split(",");for(f=0;f<e.length;f++){if(!u.data.hasOwnProperty(e[f])){c.push(e[f]+"##kvp_delim##"+u.encode(b[d]));}
u.data[e[f]]=b[d];}}}
if(!u.data.base_url){if(!u.data.secure_base_url){utag.DB("Error: No Base URL or Secure HTTPS Override Provided.");return;}else{u.data.base_url=u.data.secure_base_url;utag.DB("No Base URL provided, using Secure HTTPS Override.");}}
u.data.secure_base_url=u.data.secure_base_url||u.data.base_url;u.data.url=(location.protocol==="https:"?u.data.secure_base_url:u.data.base_url);if(u.data.url.indexOf("http")!==0&&u.data.url.indexOf("/")!==0){u.data.url=location.protocol+"//"+u.data.url;}
if(u.data.static_params){c.push(u.data.static_params);}
var cb_check=new RegExp("(\\"+u.data.qs_delim+"|"+u.data.qsp_delim+")"+u.data.cachevar+"=");if(u.data.cachebust==="enabled"&&!cb_check.test(u.data.url)){c.push([u.data.cachevar,Math.random()].join(u.data.kvp_delim));}
if(c.length>0){if(u.data.url.indexOf(u.data.qs_delim)<0){u.data.url+=u.data.qs_delim;}else if(u.data.url.indexOf(u.data.qs_delim)!==(u.data.url.length-1)){u.data.url+=u.data.qsp_delim;}}
u.data.url=u.rp(u.data.url,b)+u.rp(c.join(u.data.qsp_delim),b);u.data.url=u.data.url.replace(/##kvp_delim##/g,u.data.kvp_delim);u.callback=u.callback||function(){};if(u.data.requestscriptonce==="enabled"&&u.data.tag_type==="script"){if(!u.scriptrequested){u.scriptrequested=true;u.loader({"type":u.data.tag_type,"src":u.data.url,"loc":"script","id":"utag_90","cb":u.callback});}else{u.callback();}}else{u.loader({"type":u.data.tag_type,"src":u.data.url,"loc":"script","id":"utag_90","cb":u.callback});}
utag.DB("send:90:COMPLETE");}};utag.o[loader].loader.LOAD(id);}("90","underarmour.main"));}catch(error){utag.DB(error);}
