//tealium universal tag - utag.102 ut4.0.202110282009, Copyright 2021 Tealium.com Inc. All Rights Reserved.
try{(function(id,loader){var u={};utag.o[loader].sender[id]=u;if(utag===undefined){utag={};}if(utag.ut===undefined){utag.ut={};}if(utag.ut.loader===undefined){u.loader=function(o){var a,b,c,l;a=document;if(o.type==="iframe"){b=a.createElement("iframe");b.setAttribute("height","1");b.setAttribute("width","1");b.setAttribute("style","display:none");b.setAttribute("src",o.src);}else if(o.type==="img"){utag.DB("Attach img: "+o.src);b=new Image();b.src=o.src;return;}else{b=a.createElement("script");b.language="javascript";b.type="text/javascript";b.async=1;b.charset="utf-8";b.src=o.src;}if(o.id){b.id=o.id;}if(typeof o.cb==="function"){if(b.addEventListener){b.addEventListener("load",function(){o.cb();},false);}else{b.onreadystatechange=function(){if(this.readyState==="complete"||this.readyState==="loaded"){this.onreadystatechange=null;o.cb();}};}}l=o.loc||"head";c=a.getElementsByTagName(l)[0];if(c){utag.DB("Attach to "+l+": "+o.src);if(l==="script"){c.parentNode.insertBefore(b,c);}else{c.appendChild(b);}}};}else{u.loader=utag.ut.loader;}
u.ev={'view':1};u.initialized=false;u.map={};u.extend=[function(a,b){try{if(1){(function EpsilonPixel(pageData,uaGlobalTools){var pageID=(function getPageID(){if(pageData.page_name==='home'){return'1';}else if(pageData.page_name==='store-locator'){return'10';}else if(pageData.phx_register_success_lastpageview){return'941';}
switch(pageData.page_type){case'product-listing':return pageData.page_subcategory1?'3':'2';case'product-detail':return'5';case'cart':return'6';case'search':return'7';case'account':return'942';case'order-receipt':return'100';default:return'2';}})();switch((pageData.site_country_code||'').toLowerCase()){case'us':break;default:return;}
function getItemDiscount(idx,pageData){var lineItemDiscount=uaGlobalTools.stringMoneyAdd([(pageData.product_line_item_sourcecode_discount||[])[idx],(pageData.product_line_item_coupon_discount||[])[idx],(pageData.product_line_item_customergroup_discount||[])[idx]]);return uaGlobalTools.stringMoneyDivide(lineItemDiscount,(pageData.product_quantity)[idx]);}
if(pageData.page_type==='order-receipt'){window.dtm_config={dtmc_transaction_id:pageData.order_id,dtmc_conv_val:uaGlobalTools.stringMoneySubtract(pageData.order_subtotal,pageData.order_discount),dtmc_conv_curr:pageData.site_currency,dtmc_items:(pageData.product_sku).map(function(product,idx){return{product_id:pageData.product_sku[idx],item_amount:pageData.product_price[idx],item_quantity:pageData.product_quantity[idx],item_discount:getItemDiscount(idx,pageData)};})};}else{var subCat=pageData.product_silhouette?pageData.product_silhouette[0]:pageData.page_subcategory2;window.dtm_config={dtmc_department:pageData.product_gender?pageData.product_gender[0]:pageData.page_category,dtmc_sub_category:subCat,dtmc_upc:(pageData.product_sku||[])[0]};switch(pageData.page_type){case'product-detail':window.dtm_config.dtmc_product_id=pageData.product_style[0];window.dtm_config.dtmc_category=subCat;window.dtm_config.dtmc_sub_category=undefined;break;case'product-listing':if(pageData.page_subcategory1){window.dtm_config.dtmc_category=pageData.page_subcategory1;window.dtm_config.dtmc_sub_category=pageData.page_subcategory2;}
break;case'cart':window.dtm_config.dtmc_category='cart';break;case'search':window.dtm_config.dtmc_category='search';break;case'account':window.dtm_config.dtmc_category='account';break;default:window.dtm_config.dtmc_category=pageData.page_subcategory1;window.dtm_config.dtmc_sub_category=subCat;}}
uaGlobalTools.removeUndefinedProps(window.dtm_config);uaGlobalTools.loadScript('https://login.dotomi.com/profile/visit/js/1_0?dtm_cid=80861&dtm_cmagic=23001e&dtm_fid=101&dtm_promo_id='
+pageID
+'&cachebuster='
+Date.now(),true);})(b,utag.uaGlobalTools);}}catch(e){utag.DB(e)}}];u.send=function(a,b){if(u.ev[a]||u.ev.all!==undefined){var c,d,e,f,i;u.data={};for(c=0;c<u.extend.length;c++){try{d=u.extend[c](a,b);if(d==false)return}catch(e){}};for(d in utag.loader.GV(u.map)){if(b[d]!==undefined&&b[d]!==""){e=u.map[d].split(",");for(f=0;f<e.length;f++){u.data[e[f]]=b[d];}}}
}};utag.o[loader].loader.LOAD(id);})("102","underarmour.main");}catch(error){utag.DB(error);}
